# Generated by Django 3.2.8 on 2021-10-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMDUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m2_filename', models.CharField(max_length=30)),
                ('mml_file', models.FileField(upload_to='uploads/')),
                ('m2_file', models.FileField(blank=True, upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
