# Generated by Django 3.2.8 on 2021-11-04 16:03

import compile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0003_pmdupload_dosbox_output_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmdupload',
            name='internal_filename',
        ),
        migrations.RemoveField(
            model_name='pmdupload',
            name='m2_file',
        ),
        migrations.RemoveField(
            model_name='pmdupload',
            name='returned_m2_filename',
        ),
        migrations.AddField(
            model_name='pmdupload',
            name='directory_name',
            field=models.CharField(default='dir', max_length=10),
        ),
        migrations.AddField(
            model_name='pmdupload',
            name='pmd_output_file',
            field=models.FileField(blank=True, upload_to=compile.models.save_path),
        ),
        migrations.AlterField(
            model_name='pmdupload',
            name='dosbox_output_file',
            field=models.FileField(blank=True, upload_to=compile.models.save_path),
        ),
        migrations.AlterField(
            model_name='pmdupload',
            name='mml_file',
            field=models.FileField(upload_to=compile.models.save_path),
        ),
    ]
