# Generated by Django 3.2.8 on 2021-11-05 19:30

import compile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0004_auto_20211104_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmdupload',
            name='ff_file',
            field=models.FileField(blank=True, upload_to=compile.models.save_path),
        ),
    ]
