# Generated by Django 4.2.5 on 2023-09-08 19:15

import compile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0006_alter_pmdupload_ff_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmdupload',
            name='script_file',
            field=models.FileField(blank=True, null=True, upload_to=compile.models.save_path),
        ),
    ]
