# Generated by Django 4.2.5 on 2023-09-08 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0007_pmdupload_script_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmdupload',
            name='directory_name',
        ),
        migrations.RemoveField(
            model_name='pmdupload',
            name='id',
        ),
        migrations.AddField(
            model_name='pmdupload',
            name='uuidterm',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
