# Generated by Django 4.2.5 on 2023-09-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0008_remove_pmdupload_directory_name_remove_pmdupload_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmdupload',
            name='dosbox_output_file',
        ),
        migrations.RemoveField(
            model_name='pmdupload',
            name='ff_file',
        ),
    ]
