# Generated by Django 4.2.5 on 2023-09-12 07:07

import compile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0010_pmdupload_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmdupload',
            name='m2file',
            field=models.FileField(blank=True, upload_to=compile.models.save_path),
        ),
    ]
