# Generated by Django 4.2.5 on 2023-09-13 02:08

import compile.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compile', '0011_pmdupload_m2file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrafile', models.FileField(blank=True, null=True, upload_to=compile.models.extrafile_savepath)),
                ('pmdupload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compile.pmdupload')),
            ],
        ),
    ]
